# Generated by Django 3.2.7 on 2025-12-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staff',
            new_name='feedback_tbl',
        ),
        migrations.RenameField(
            model_name='feedback_tbl',
            old_name='email',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='feedback_tbl',
            old_name='password',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
