# Generated by Django 3.2.7 on 2025-12-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_auto_20251224_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_tbl',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='program_images/'),
        ),
    ]
