# Generated by Django 3.2.7 on 2025-12-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_program_tbl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_details',
            name='status',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='program_tbl',
            name='image',
            field=models.FileField(default=1, max_length=250, upload_to=''),
            preserve_default=False,
        ),
    ]
